# Fichier: .github/workflows/retrain_model.yml (Version Finale et Robuste)
name: Entraînement des Modèles

on:
  workflow_dispatch:
    inputs:
      category_id:
        description: "L'ID unique du modèle à entraîner (ex: ligne1_category1_01)"
        required: true
        default: 'ligne1_category1_01'

jobs:
  training:
    runs-on: ubuntu-latest
    
    # --- AJOUT CRUCIAL : Définir le répertoire de travail ---
    defaults:
      run:
        working-directory: ./service-ia-python

    steps:
      - name: Checkout du code
        uses: actions/checkout@v3

      - name: Mise en place de Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Installation des dépendances
        run: |
          pip install "numpy<2.0" protobuf==3.20.3
          pip install -r requirements.txt
      
      # --- Étape de débogage (très utile) ---
      - name: Vérifier la structure des fichiers
        run: ls -R
      
      - name: Lancer l'entraînement
        env:
          MLFLOW_TRACKING_URI: ${{ secrets.MLFLOW_TRACKING_URI }}
        run: |
          python3 app/train.py --category ${{ github.event.inputs.category_id }}