# Fichier: .github/workflows/retrain_model.yml (Corrigé pour l'exécution en module)
name: Entraînement Manuel des Modèles

on:
  workflow_dispatch:
    inputs:
      category_id:
        description: "L'ID unique du modèle à entraîner (ex: ligne1_category1_01)"
        required: true
        default: 'ligne1_category1_01'

jobs:
  training:
    runs-on: ubuntu-latest
    
    defaults:
      run:
        working-directory: ./service-ia-python

    steps:
      - name: Checkout du code
        uses: actions/checkout@v3

      - name: Mise en place de Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Installation des dépendances
        run: |
          python -m pip install --upgrade pip
          pip install "numpy<2.0" protobuf==3.20.3
          pip install -r requirements.txt
      
      - name: Lancer l'entraînement du modèle
        env:
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
          DB_HOST: ${{ secrets.DB_HOST }}
          DB_USER: ${{ secrets.DB_USER }}
          DB_NAME: ${{ secrets.DB_NAME }}
          DB_PORT: ${{ secrets.DB_PORT }}
          COMET_API_KEY: ${{ secrets.COMET_API_KEY }}
          COMET_PROJECT_NAME: ${{ secrets.COMET_PROJECT_NAME }}
        run: |
          # <<< LA CORRECTION EST ICI >>>
          # On lance le script en tant que module pour que les imports fonctionnent.
          python -m app.train --category ${{ github.event.inputs.category_id }}