# Fichier: .github/workflows/retrain_model.yml
name: Entraînement des Modèles

on:
  workflow_dispatch:
    inputs:
      category_id:
        description: "L'ID unique du modèle à entraîner (ex: ligne1_category1_01)"
        required: true
        default: 'ligne1_category1_01'

jobs:
  training:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout du code
        uses: actions/checkout@v3

      - name: Mise en place de Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Installation des dépendances
        run: |
          # On installe les paquets sensibles en premier avec des versions fixes
          pip install "numpy<2.0" protobuf==3.20.3
          # On installe le reste depuis le fichier requirements
          pip install -r service-ia-python/requirements.txt
      
      # --- BLOC CORRIGÉ ---
      - name: Lancer l'entraînement
        env:
          MLFLOW_TRACKING_URI: ${{ secrets.MLFLOW_TRACKING_URI }}
        run: |
          # On se place dans le dossier du service AVANT de lancer le script
          cd service-ia-python
          
          # Maintenant on lance le script depuis cet emplacement
          python3 app/train.py --category ${{ github.event.inputs.category_id }}