# Fichier: .github/workflows/retrain_model.yml (Corrigé et simplifié)
name: Entraînement Manuel des Modèles

on:
  workflow_dispatch:
    inputs:
      category_id:
        description: "L'ID unique du modèle à entraîner (ex: ligne1_category1_01)"
        required: true
        default: 'ligne1_category1_01'

jobs:
  training:
    runs-on: ubuntu-latest
    
    # Définit le répertoire de travail pour toutes les commandes 'run'
    defaults:
      run:
        working-directory: ./service-ia-python

    steps:
      - name: Checkout du code
        uses: actions/checkout@v3

      - name: Mise en place de Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Installation des dépendances
        run: |
          python -m pip install --upgrade pip
          pip install "numpy<2.0" protobuf==3.20.3
          pip install -r requirements.txt
      
      # --- Étape de débogage (optionnelle mais utile) ---
      - name: Vérifier la structure des fichiers avant l'entraînement
        run: ls -R

      - name: Lancer l'entraînement du modèle
        env:
          # --- Secrets pour la connexion à Supabase ---
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
          DB_HOST: ${{ secrets.DB_HOST }}
          DB_USER: ${{ secrets.DB_USER }}
          DB_NAME: ${{ secrets.DB_NAME }}
          DB_PORT: ${{ secrets.DB_PORT }}
          # --- Secrets pour la connexion à Comet ML ---
          COMET_API_KEY: ${{ secrets.COMET_API_KEY }}
          COMET_PROJECT_NAME: ${{ secrets.COMET_PROJECT_NAME }}
        run: |
          python app/train.py --category ${{ github.event.inputs.category_id }}