# Fichier: .github/workflows/scheduled_retraining.yml (Version finale et robuste)
name: Entraînement Mensuel Automatisé sur Vertex AI

on:
  schedule:
    - cron: '0 2 1 * *' # Se lance le premier jour de chaque mois à 2h du matin
  workflow_dispatch:
    inputs:
      category_id:
        description: "ID du modèle à entraîner"
        required: true
        default: 'ligne1_category1_01'

jobs:
  train-on-vertex-ai:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout du code
        uses: actions/checkout@v3

      - name: Authentification à Google Cloud
        uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: '${{ secrets.GCP_SA_KEY }}'

      - name: Mise en place de gcloud CLI
        uses: 'google-github-actions/setup-gcloud@v2'

      - name: Configurer Docker pour Google Artifact Registry
        run: gcloud auth configure-docker europe-west1-docker.pkg.dev

      - name: Build et Push de l'image d'entraînement
        run: |
          IMAGE_URI=europe-west1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/app-images/sales-forecasting-trainer:latest
          docker build -t $IMAGE_URI -f service-ia-python/training.Dockerfile ./service-ia-python
          docker push $IMAGE_URI

      - name: Lancer le job d'entraînement sur Vertex AI
        run: |
          # On prépare l'URI de l'image Docker
          IMAGE_URI=europe-west1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/app-images/sales-forecasting-trainer:latest

          # On crée le fichier de configuration pour le job Vertex AI.
          # Cette méthode est la plus fiable.
          cat <<EOF > job.yaml
          displayName: training-job-${{ github.event.inputs.category_id }}-${{ github.run_id }}
          jobSpec:
            workerPoolSpecs:
            - machineSpec:
                machineType: n1-standard-4
                acceleratorType: NVIDIA_TESLA_L4
                acceleratorCount: 1
              replicaCount: 1
              containerSpec:
                imageUri: ${IMAGE_URI}
                args:
                - --category
                - ${{ github.event.inputs.category_id }}
                env:
                - name: MLFLOW_TRACKING_URI
                  value: "${{ secrets.MLFLOW_TRACKING_URI }}"
          EOF

          # On lance le job en utilisant le fichier de configuration
          gcloud ai custom-jobs create \
            --region=us-east1 \
            --config=job.yaml