# Fichier: .github/workflows/scheduled_retraining.yml (Version finale avec la bonne région)
name: Entraînement Mensuel Automatisé sur Vertex AI

on:
  schedule:
    - cron: '0 2 1 * *'
  workflow_dispatch:
    inputs:
      category_id:
        description: "ID du modèle à entraîner"
        required: false
        default: 'ligne1_category1_01'

jobs:
  train-on-vertex-ai:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout du code
        uses: actions/checkout@v3

      - name: Authentification à Google Cloud
        uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: '${{ secrets.GCP_SA_KEY }}'

      - name: Mise en place de gcloud CLI
        uses: 'google-github-actions/setup-gcloud@v2'

      - name: Configurer Docker pour Google Artifact Registry
        run: gcloud auth configure-docker europe-west1-docker.pkg.dev --quiet

      - name: Build et Push de l'image d'entraînement
        run: |
          IMAGE_URI=europe-west1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/app-images/sales-forecasting-trainer:latest
          docker build -t $IMAGE_URI -f service-ia-python/training.Dockerfile ./service-ia-python
          docker push $IMAGE_URI

      - name: Lancer le job d'entraînement sur Vertex AI
        run: |
          IMAGE_URI=europe-west1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/app-images/sales-forecasting-trainer:latest
          
          CATEGORY_ID="${{ github.event.inputs.category_id || 'ligne1_category1_01' }}"
          
          JOB_NAME="training-job-${CATEGORY_ID//_/-}-${{ github.run_id }}"
          
          cat <<EOF > config.yaml
          workerPoolSpecs:
          - machineSpec:
              machineType: n1-standard-4
              acceleratorType: NVIDIA_TESLA_T4
              acceleratorCount: 1
            replicaCount: 1
            containerSpec:
              imageUri: $IMAGE_URI
              args:
              - --category
              - $CATEGORY_ID
              env:
              - name: MLFLOW_TRACKING_URI
                value: "${{ secrets.MLFLOW_TRACKING_URI }}"
          EOF
          
          echo "--- Contenu de config.yaml ---"
          cat config.yaml
          echo "-----------------------------"
          
          # On lance le job dans la région où les quotas sont probablement disponibles
          gcloud ai custom-jobs create \
            --region=europe-west1 \
            --display-name=$JOB_NAME \
            --config=config.yaml