# Fichier: .github/workflows/scheduled_retraining.yml (Version Corrigée)
name: Entraînement Mensuel Automatisé sur Vertex AI

on:
  schedule:
    - cron: '0 2 1 * *'
  workflow_dispatch:
    inputs:
      category_id:
        description: "ID du modèle à entraîner"
        required: true
        default: 'ligne1_category1_01'

jobs:
  train-on-vertex-ai:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout du code
        uses: actions/checkout@v3

      - name: Authentification à Google Cloud
        uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: '${{ secrets.GCP_SA_KEY }}'

      - name: Mise en place de gcloud CLI
        uses: 'google-github-actions/setup-gcloud@v2'

      - name: Configurer Docker pour Google Artifact Registry
        # Remplacez 'europe-west1' par votre région si elle est différente
        run: gcloud auth configure-docker europe-west1-docker.pkg.dev

      - name: Build et Push de l'image d'entraînement
        run: |
          IMAGE_URI=europe-west1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/app-images/sales-forecasting-trainer:latest
          docker build -t $IMAGE_URI -f service-ia-python/training.Dockerfile ./service-ia-python
          docker push $IMAGE_URI

      - name: Lancer le job d'entraînement sur Vertex AI
        run: |
          IMAGE_URI=europe-west1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/app-images/sales-forecasting-trainer:latest
          gcloud ai custom-jobs create \
            --region=us-east1 \
            --display-name="training-job-${{ github.event.inputs.category_id }}-${{ github.run_id }}" \
            --worker-pool-spec=machine-type=n1-standard-4,replica-count=1,accelerator-type=NVIDIA_TESLA_L4,accelerator-count=1,container-image-uri=$IMAGE_URI \
            --args=--category,${{ github.event.inputs.category_id }} \
            --environment-variables="MLFLOW_TRACKING_URI=${{ secrets.MLFLOW_TRACKING_URI }}"